set_project("elysia_prefab")
set_languages("cxx23")
set_toolchains("clang")
add_rules("mode.debug", "mode.release")
option("ecs_headers")
    set_default("../../ElysiaECS_Hpp/include")
    set_description("Path to the canonical Elysia header implementation")
option_end()
option("module")
    set_default(false)
    set_description("Build the thin header-backed module interface and smoke test")
option_end()
add_requires("nameof", "gtest")
add_requires("reflect-cpp 0.24.0", {configs = {msgpack = true, flatbuffers = true, toml = true}})
target("ElysiaPrefab")
    set_kind("headeronly")
    add_includedirs("include", get_config("ecs_headers"), {public = true})
    add_packages("nameof", "reflect-cpp", {public = true})
target_end()
if has_config("module") then
    target("ElysiaPrefabModule")
        set_kind("static")
        add_deps("ElysiaPrefab")
        set_policy("build.c++.modules", true)
        add_files("module/elysia_prefab.cppm", {public = true})
    target_end()
    target("prefab_module_smoke")
        set_kind("binary")
        add_deps("ElysiaPrefabModule")
        add_files("module/smoke.cpp")
    target_end()
end
target("prefab_tests")
    set_kind("binary")
    add_deps("ElysiaPrefab")
    add_packages("gtest")
    add_files("tests/*.cpp")
    set_rundir(os.scriptdir())
target_end()
target("prefab_car")
    set_kind("binary")
    add_deps("ElysiaPrefab")
    add_files("examples/car.cpp")
    set_rundir(os.scriptdir())
target_end()
